### ISSUE TITLE
UPI apps are not detecting

### ISSUE THREAD

**Issue by phanindravarma412** [drenther/upi_pay#29] opened 2021-06-05 17:54 UTC

**Comment by reeteshranjan** [comment] 2021-06-06 03:29
Please check if this is same as #25.

Please include more details:
1. Which mobile platform? (e.g. Android, iOS, both)
2. Mobile platform version? (e.g. Android 11, iOS 14)
2. Which upi_pay package version?
3. Which apps are installed on your mobile phone?

**Comment by phanindravarma412** [comment] 2021-06-06 09:12
I am using Android 11 and package version is ^1.0.0 and installed mobile apps are Phonepay and Gpay.

**Comment by reeteshranjan** [comment] 2021-06-06 13:25
@drenther this seems to be a duplicate of #25 . I don't have an Android 11 phone to test.

**Comment by drenther** [comment] 2021-06-06 13:28
Hmm. Looks like the same issue. I will try to get my hands on an Android 11 and test.

**Comment by phanindravarma412** [comment] 2021-06-06 16:10
Even I checked on another android 10 device, UPI apps are not detecting.

**Comment by parmarravi** [comment] 2021-06-10 04:14
Android has added additional permission to query the package of the app installed.  without this it will not detect the apps on phone after android 30 and above  
I have tried this , but no luck 
https://stackoverflow.com/questions/67909269/how-to-detect-upi-in-android-11-in-flutter

**Comment by drenther** [comment] 2021-06-10 05:10
This issue is tracked at #25. Closing it here.

**Closed by drenther** 2021-06-10 05:10 UTC
Labels: duplicate

**Comment by reeteshranjan** [comment] 2021-06-20 08:30
@parmarravi @phanindravarma412 please check updates on #25 .

**Comment by reeteshranjan** [comment] 2021-06-24 06:36
@parmarravi @phanindravarma412 there are more updates on #25 . Please check.

**Comment by reeteshranjan** [comment] 2022-02-05 04:21
Is https://github.com/drenther/upi_pay/issues/38 relevant and important for you?

If yes, could you please respond to my twitter thread with UPI and NPCI handles included in your response asking how these must be solved and how it helps you? https://twitter.com/reeteshr08/status/1488746633068089345

@parmarravi @phanindravarma412
