### ISSUE TITLE
The plugin `upi_pay` uses a deprecated version of the Android embedding.

### ISSUE THREAD

**Issue by MominRaza** [drenther/upi_pay#52] opened 2022-02-11 17:40 UTC
### Describe the bug
The plugin `upi_pay` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2    
embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.      
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding:
https://flutter.dev/go/android-plugin-migration.

**Comment by RamSakamuri** [comment] 2022-02-14 02:38
@drenther  Could you please advice work around or fix for this issue

**Comment by drenther** [comment] 2022-02-15 05:02
Duplicate of #44

**Closed by drenther** 2022-02-15 05:02 UTC
Labels: bug
