### ISSUE TITLE
Getting Error "U16: Risk Threshold Exceeded" in BHIM, Google Pay & Amazon Pay

### ISSUE THREAD

**Issue by jatinyadav25** [drenther/upi_pay#19] opened 2020-10-26 08:31 UTC
Getting U16 error in BHIM, Google Pay & Amazon Pay. Although payment was successfully transferred in Phonepe.

UpiTransactionResponse txnResponse = await UpiPay.initiateTransaction(
                      amount: "10.00",
                      app: UpiApplication.bhim,
                      receiverName: "Birendra Singh",
                      receiverUpiAddress: "xxxxxxx@upi",
                      transactionRef: 'ORD4',
                      transactionNote: 'Test transaction'
);

**Comment by drenther** [comment] 2020-10-26 17:36
Duplicate of #18

**Comment by mangeshsvk** [comment] 2020-10-27 10:13
Hi, I am new to flutter but have a good understanding of programming. I was working with embedded c developments before. If you provide me some sort of documentation for this, I would like to contribute to this issue.

**Comment by reeteshranjan** [comment] 2020-10-28 08:54
Have you verified that your issue is not related to any of these:

https://www.quora.com/How-can-I-resolve-the-issue-of-risk-threshold-exceeded-from-the-BHIM-app-I-am-not-able-to-do-any-transactions

And this excerpt from https://www.npci.org.in/what-we-do/bhim/faq:

"Why Do I See ‘Risk Threshold Exceeded’?
A user on BHIM can make only 10 financial transactions per day and the total of these transactions cannot exceed Rs. 40,000.

Once you’ve exceeded your daily transaction limit, you’ll receive the ‘Risk threshold exceeded’ notification."

**Comment by jatinyadav25** [comment] 2020-10-29 06:31
@reeteshranjan Yes, I verified it was not because of the transaction limit and also tested the same with first transaction of the day; Although payment was successful through Phonepe app but failed in BHIM, Google Pay & Amazon Pay;

**Comment by mangeshsvk** [comment] 2020-10-29 06:46
I also noticed editing the amount at the time of payment also does not work. So why don't you break this problem into pieces and try?

1. Like invoke GooglePay using intent and then add payment amount and then try. If that works we can figure a way out.
2. If that also doesn't work don't pass anything just open google pay from the app and try.

**Comment by manojsinghal2003** [comment] 2020-11-03 10:54
Please let me know what is the workaround, I am also facing the same issue.

**Comment by manojsinghal2003** [comment] 2020-11-05 15:15
Please let us know the plan, I need to fix this issue on urgent basis... if there is no plan to fix, Please highlight so that I can explore other options. Thanks.

**Comment by drenther** [comment] 2020-11-05 15:23
This is not an issue that can be fully resolved from our end i.e. not something a plugin can handle.

Feel free to look for alternative.

**Comment by manojsinghal2003** [comment] 2020-11-05 15:25
can you suggest any workaround that will help us to fix this?

**Comment by drenther** [comment] 2020-11-11 05:16
If you are using this for P2M kind of payment, make sure to pass the correct merchantCode (mcc). For P2P payments, we are already doing what we can and any failure means you will need to actively avoid that app for now.

**Comment by drenther** [comment] 2020-11-17 08:38
There is no workaround that can be done from a plugin point of view as of now. I am keeping this issue open so that we don't have duplicate issues opened for the same.

But, we won't be replying to any more comments on status update as there is nothing to update here.

Feel free to add on if you have any findings. But as of now this thread is in "READ-ONLY" mode.

**Comment by reeteshranjan** [comment] 2021-04-19 19:40
Please see and review https://github.com/drenther/upi_pay/pull/17

**Comment by drenther** [comment] 2021-06-04 19:06
Addressed in #17. Any further issue on the same ground should be raised separately.

**Closed by drenther** 2021-06-04 19:06 UTC

**Comment by reeteshranjan** [comment] 2021-06-05 06:19
@jatinyadav25 @mangeshsvk @manojsinghal2003 wanted to add my update as contributor for recent update that includes multiple apps. And add some more data on why this bug is OK to close here.

Based on testing it's very clearly understood that these errors have nothing to do with this package's logic/code. Please see the following:

1. It's seen that when these apps give this error, other working apps payments go through within next 5 minutes, without any bank account specific issue. So the errors reported by these apps do not reflect a real bank account related issue; but it's got to do something with the protocol between the UPI payment app and the banks.

2. The package only provides form-filling data which is seen to be clearly filled in the UPI payment app. The security error reported seems to be due to using non-merchant payments. I am very close to verifying this theory with already some testing done that clearly shows that.

However; if you think that the package must support merchant payments, too, before closing this bug, please feel free to do so.

**Comment by reeteshranjan** [comment] 2021-07-09 12:01
@jatinyadav25 @mangeshsvk @manojsinghal2003 please follow #38

**Comment by reeteshranjan** [comment] 2022-02-05 04:23
Is https://github.com/drenther/upi_pay/issues/38 relevant and important for you?

If yes, could you please respond to my twitter thread with UPI and NPCI handles included in your response asking how these must be solved and how it helps you? https://twitter.com/reeteshr08/status/1488746633068089345

@jatinyadav25 @manojsinghal2003 @mangeshsvk

**Comment by anjamma32** [comment] 2025-03-13 12:58
Sir my problem phonepay u16_NPCI_TXNRISK_10154sir problem phonepay send and receive no money my account sir my  request
