### ISSUE TITLE
Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type Activity?

### ISSUE THREAD

**Issue by Electro-17** [drenther/upi_pay#77] opened 2023-03-26 11:52 UTC
Just installed the plugin and tried to make build, then got the below error.

e: C:\Users\user\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\upi_pay-1.0.1\android\src\main\kotlin\com\drenther\upi_pay\UpiPayPlugin.kt: (78, 42): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type Activity?
e: C:\Users\user\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\upi_pay-1.0.1\android\src\main\kotlin\com\drenther\upi_pay\UpiPayPlugin.kt: (83, 15): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type Activity?
e: C:\Users\user\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\upi_pay-1.0.1\android\src\main\kotlin\com\drenther\upi_pay\UpiPayPlugin.kt: (97, 34): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type Activity?

**Comment by drenther** [comment] 2023-03-26 12:11
Duplicate of #60

**Closed by drenther** 2023-03-26 12:11 UTC
Labels: bug, duplicate
