### ISSUE TITLE
Facing issue in SBI Pay - Uri Decode

### ISSUE THREAD

**Issue by senthil88** [drenther/upi_pay#1] opened 2020-04-19 11:46 UTC
@ symbol is not decoding properly in SBI Pay app alone.

**For example** 
"xxxx@okhdfcbank" is working in all other apps.

In SBI pay alone it's not decoding properly. It's  coming as   "xxxx 40okhdfcbank"

**Comment by pepsighan** [comment] 2020-04-21 07:51
@senthil88 Could you provide a reproducible code?

**Comment by drenther** [comment] 2020-07-26 05:15
It looks like it is an issue of SBIPay not following the spec strictly speaking. Closing this since it's not something we can handle on a library level.

**Closed by drenther** 2020-07-26 05:15 UTC

**Comment by reeteshranjan** [comment] 2021-06-05 06:36
@senthil88 some apps like SBIPay are not able to properly decode URL encoded VPAs. This was worked around in the Android intent calling code by not URL encoding the VPA. This works across all apps including those like SBI Pay that got confused with the URL encoded VPAs. It's available in v0.3.0+.

**Comment by reeteshranjan** [comment] 2022-02-05 04:27
Is https://github.com/drenther/upi_pay/issues/38 relevant and important for you?

If yes, could you please respond to my twitter thread with UPI and NPCI handles included in your response asking how these must be solved and how it helps you? https://twitter.com/reeteshr08/status/1488746633068089345

@senthil88
